const {_electron}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let app,page;
(async()=>{
const data=await fs.mkdtemp(path.join(os.tmpdir(),'quiet-books-')),file=path.join(data,'书评测试.txt'),text=Array.from({length:160},(_,i)=>`第${i+1}段 山海星辰与𠀀字，故事沿着小路继续。`).join('\n');await fs.writeFile(file,text);const env={...process.env,QUIET_READER_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
async function launch(){app=await _electron.launch({args:[root],env});page=await app.firstWindow();await page.waitForSelector('#shelf-import');}
await launch();await page.locator('#file-input').setInputFiles(file);await page.click('#import-confirm');await page.waitForFunction(()=>window.readerDiagnostics?.().id&&!window.readerDiagnostics().opening&&!window.readerDiagnostics().working);await page.keyboard.press('Escape');await page.click('#review-button');await page.selectOption('#review-rating','5');await page.fill('#review-tags','科幻，重读');await page.fill('#review-text','星辰与山海，值得重读。');await page.click('#review-save');await page.waitForSelector('#book-review',{state:'hidden'});
await page.click('#search-button');await page.fill('#query','第80段');await page.click('#search-submit');await page.locator('.match').first().click();await page.waitForTimeout(650);assert.equal(await page.evaluate(()=>window.readerDiagnostics().highlight.paragraph),79);await page.click('#library-button');await page.waitForFunction(()=>window.readerDiagnostics().screenMode==='library');assert.match(await page.locator('.book-review-summary').textContent(),/★★★★★.*科幻/);
const books=await page.evaluate(()=>window.reader.library());assert.equal(books[0].counts.total,Array.from(text.replace(/\s/gu,'')).length);assert.ok(books[0].counts.read>0&&books[0].counts.read<books[0].counts.total);assert.match(await page.locator('.book-progress').textContent(),/%.*\/.*字/);
const output=path.join(data,'export.txt');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},output);await page.getByRole('button',{name:'导出 TXT',exact:true}).click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('TXT 已导出'));assert.equal(await fs.readFile(output,'utf8'),text);
await page.click('.book');await page.waitForFunction(()=>!window.readerDiagnostics().opening&&!window.readerDiagnostics().working);await page.keyboard.press('Escape');await page.waitForFunction(()=>!window.readerDiagnostics().working);await page.locator('#reading-progress').evaluate(el=>{el.value=10000;el.dispatchEvent(new Event('input'));});await page.waitForTimeout(300);await page.click('#library-button');await page.waitForFunction(()=>window.readerDiagnostics().screenMode==='library');assert.match(await page.locator('.book-progress').textContent(),/^100.0%/);
const exited=new Promise(r=>app.process().once('exit',r));await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await exited;await launch();await page.waitForSelector('.book-progress');assert.match(await page.locator('.book-progress').textContent(),/^100.0%/);await page.locator('.book-actions').getByRole('button',{name:'书评',exact:true}).click();assert.equal(await page.locator('#review-rating').inputValue(),'5');assert.equal(await page.locator('#review-text').inputValue(),'星辰与山海，值得重读。');await page.click('[data-close="book-review"]');await page.screenshot({path:path.join(root,'test-results/books-progress-review.png')});await app.close();console.log('PASS review persistence, tags, Unicode word counts, search jump, shelf progress and TXT export');
})().catch(async e=>{console.error(e);await app?.close();process.exitCode=1;});
