// Opt-in integration test: creates two temporary accounts, writes cleanup SQL.
const {CloudSync}=require('../src/cloud-sync.cjs'),{Store}=require('../src/store.cjs'),{identity,defaults}=require('../src/core.cjs');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
let transportApp;
(async()=>{
const {_electron}=require('playwright');const transportEnv={...process.env,QUIET_READER_DATA:await fs.mkdtemp(path.join(os.tmpdir(),'quiet-net-test-'))};delete transportEnv.ELECTRON_RUN_AS_NODE;transportApp=await _electron.launch({args:[path.resolve(__dirname,'..')],env:transportEnv});
const rpc=(name,args)=>transportApp.evaluate(async({net},{name,args,config})=>{const response=await net.fetch(config.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify(args)});const body=await response.text();const data=body?JSON.parse(body):null;if(!response.ok)throw new Error(data.message||'RPC failed');return data;},{name,args,config:require('../src/cloud-config.json')});
const suffix=crypto.randomBytes(5).toString('hex'),names=['qr_test_a_'+suffix,'qr_test_b_'+suffix],password=crypto.randomBytes(20).toString('hex');await fs.mkdir(path.join(__dirname,'../test-results'),{recursive:true});await fs.writeFile(path.join(__dirname,'../test-results/cloud-cleanup.sql'),`delete from public.quiz_users where username in ('${names[0]}','${names[1]}');`);
for(const name of names)await rpc('quiz_register_user',{p_username:name,p_password:password});const a=await rpc('reader_login',{p_username:names[0],p_password:password}),a2=await rpc('reader_login',{p_username:names[0],p_password:password}),b=await rpc('reader_login',{p_username:names[1],p_password:password});
async function store(){const s=new Store(await fs.mkdtemp(path.join(os.tmpdir(),'quiet-live-cloud-')));await s.init();return s;}
const one=await store(),two=await store(),other=await store();const bytes=Buffer.from('山海星辰与长篇小说。\n'.repeat(15000)),id=identity(bytes);await fs.writeFile(one.file(id,'txt'),bytes);await one.write({id,title:'云同步测试',encoding:'utf-8',size:bytes.length,settings:defaults,window:{width:960,height:780},progress:null,counts:{total:180000,read:0},review:{rating:4,tags:['测试'],text:'跨设备书评',updated:100}});
await one.updatePreferences(p=>{p.dayCounters={device_one:{'2026-10-06':{[id]:4000}}};p.studio={fields:{source:'山海, 10'}};});
const A=new CloudSync(one,a,'device_one',rpc),B=new CloudSync(two,a2,'device_two',rpc),C=new CloudSync(other,b,'device_other',rpc);assert.ok((await A.run()).uploaded>0);await B.run();assert.deepEqual(await fs.readFile(two.file(id,'txt')),bytes);assert.equal((await two.read(id)).review.text,'跨设备书评');assert.equal((await two.preferences()).days['2026-10-06'][id],4000);await C.run();assert.equal((await other.list()).length,0);assert.equal(await rpc('reader_get',{p_token:b.token,p_key:`book/${id}/base`}),null);await assert.rejects(rpc('reader_list',{p_token:'invalid',p_after:''}));
const config=require('../src/cloud-config.json');const statusCode=await transportApp.evaluate(async({net},config)=>(await net.fetch(config.url+'/rest/v1/reader_objects?select=key',{headers:{apikey:config.key}})).status,config);assert.ok([401,403].includes(statusCode),'anonymous direct table access denied');
await one.updateBook(id,v=>v.review.text='甲');await two.updateBook(id,v=>v.review.text='乙');await A.run();const conflict=await B.run();assert.ok(conflict.conflicts.includes(`book/${id}/review`));await B.resolve(`book/${id}/review`,'local');await A.run();assert.equal((await one.read(id)).review.text,'乙');
// Exercise the desktop login IPC and per-account cache without user credentials.
const env={...process.env,QUIET_READER_DATA:await fs.mkdtemp(path.join(os.tmpdir(),'quiet-auth-ui-'))};delete env.ELECTRON_RUN_AS_NODE;const app=transportApp;try{let page=await app.firstWindow();await page.click('#account-button');await page.fill('#cloud-username',names[1]);await page.fill('#cloud-password',password);await page.uncheck('#cloud-import-local');await page.click('#cloud-login-submit');await page.waitForFunction(()=>document.getElementById('cloud-account-status').textContent.includes('同步完成'),null,{timeout:120000});const status=await page.evaluate(()=>window.reader.cloudStatus());assert.equal(status.user.username,names[1]);const encrypted=await fs.readFile(path.join(transportEnv.QUIET_READER_DATA,'cloud-session.bin'));assert.ok(!encrypted.includes(Buffer.from(names[1])));await app.close();transportApp=await _electron.launch({args:[path.resolve(__dirname,'..')],env:transportEnv});page=await transportApp.firstWindow();await page.waitForFunction(async()=>!!(await window.reader.cloudStatus()).user);assert.equal((await page.evaluate(()=>window.reader.cloudStatus())).user.username,names[1]);await page.click('#account-button');await page.click('#cloud-logout');await page.waitForFunction(async()=>!(await window.reader.cloudStatus()).user);assert.equal(await page.locator('#cloud-password').inputValue(),'');}finally{}
await rpc('reader_logout',{p_token:a.token});await assert.rejects(rpc('reader_list',{p_token:a.token,p_after:''}));await rpc('reader_logout',{p_token:a2.token});await rpc('reader_logout',{p_token:b.token});console.log('PASS LIVE: quiz accounts, multi-chunk book transfer, progress/review/draft/time restore, account isolation, RLS denial, conflicts, logout revocation, desktop login');
})().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(async()=>{await transportApp?.close();});
