const {_electron}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');let app,page;
(async()=>{
 const data=await fs.mkdtemp(path.join(os.tmpdir(),'quiet-interaction-')),file=path.join(data,'一个很长很长的小说标题测试书架是否发生文字溢出.txt');
 const original='第一章 夜雨\n更多免费小说请访问 example.com\n'+'少年沿着小路慢慢前行，风带来了树林的气息。山海与星辰之间，故事继续。\n'.repeat(100);await fs.writeFile(file,original);
 const env={...process.env,QUIET_READER_DATA:data};delete env.ELECTRON_RUN_AS_NODE;app=await _electron.launch({args:[root],env});page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.locator('#file-input').setInputFiles(file);await page.waitForSelector('#import-options[open]');assert.equal(await page.locator('#clean-enabled').isChecked(),false);await page.check('#clean-enabled');await page.check('#clean-presets input[value="download"]');await page.click('#import-confirm');assert.match(await page.locator('#clean-preview-output').textContent(),/请先预览/);await page.click('#clean-preview');await page.waitForFunction(()=>document.getElementById('clean-preview-output').textContent.includes('命中 1 行'));await page.click('#import-confirm');await page.waitForFunction(()=>window.readerDiagnostics?.().id&&!window.readerDiagnostics().opening&&!window.readerDiagnostics().working);
 assert.equal(await fs.readFile(file,'utf8'),original);const id=await page.evaluate(()=>window.readerDiagnostics().id);assert.equal(await fs.readFile(path.join(data,'books',id+'.original.txt'),'utf8'),original);assert.doesNotMatch(await fs.readFile(path.join(data,'books',id+'.txt'),'utf8'),/example.com/);
 assert.equal(await page.locator('header').isVisible(),false);await page.screenshot({path:path.join(root,'test-results/native-pure.png')});
 await page.mouse.move(110,134);await page.mouse.down();await page.mouse.move(510,135,{steps:20});await page.mouse.up();assert.equal(await page.locator('header').isVisible(),false);await page.keyboard.press('Meta+c');const copied=await app.evaluate(({clipboard})=>clipboard.readText());assert.ok(copied.length>3,copied);assert.ok(original.includes(copied));
 await page.keyboard.press('Escape');if(process.platform==='darwin')assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getWindowButtonPosition()));await page.click('#library-button');await page.waitForFunction(()=>window.readerDiagnostics().screenMode==='library');await page.screenshot({path:path.join(root,'test-results/shelf-fixed.png')});
 await page.click('#cloud-button');const studio=page.frameLocator('#studio-frame');await studio.locator('#palettes').scrollIntoViewIfNeeded();assert.equal(await studio.locator('#palettes').evaluate(el=>el.scrollWidth<=el.clientWidth),true);await page.screenshot({path:path.join(root,'test-results/palettes-fixed.png')});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(560,700));await page.waitForTimeout(300);assert.equal(await studio.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth),true);await studio.locator('#studio-back').click();await page.waitForFunction(()=>window.readerDiagnostics().screenMode==='library');assert.equal(await page.locator('#library').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS cleaning preview and original backup, selectable/copyable text, native traffic lights, palette and shelf overflow');await app.close();
})().catch(async e=>{console.error(e);if(page)await page.screenshot({path:path.join(root,'test-results/interaction-failure.png')});await app?.close();process.exitCode=1;});
