const $=id=>document.getElementById(id),canvas=$('canvas');
const palettes=[['#284c3d','#54775b','#849c72','#bd794d','#b0b78d'],['#c94232','#ec794a','#dda330','#853d39','#d5696a'],['#1ea6b0','#4593be','#77ccd0','#a2bacd','#427897'],['#202622','#515951','#8b958b','#b0b6a8','#364238']];
const sample=`设计, 100\n灵感, 82\n创造力, 76\n文字, 66\n自然, 60\n自由, 56\n想象, 52\n生活, 48\n艺术, 46\n故事, 44\n探索, 42\n表达, 40\n色彩, 38\n热爱, 36\n未来, 34\n温度, 32\n美好, 30\n生长, 28\n连接, 26\n诗意, 25\n世界, 24\n可能, 23\n日常, 22\n节奏, 21\n光影, 20\n陪伴, 19\n旅程, 18\n好奇, 17\n细节, 16\n感知, 15\n山野, 14\n风, 13\n共鸣, 12\n留白, 11\n心动, 10\n发现, 9\nWORDLOOM, 18\nIDEAS, 15\nCREATE, 12\nSTORIES, 10`;
let mode='text',shape='circle',palette=0,running=false,drawn=0,total=0;
let customStopwords=new Set();
$('source').value='设计源于生活，灵感源于自然。设计让文字成为艺术，让艺术走进生活。创造力连接想象与未来，自由表达让灵感生长。我们热爱设计，热爱自然，热爱生活的诗意与美好。';
document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='text'));
$('hint').textContent='自动分词后过滤虚词、口语词、单字、标点，并优先合并常见短语。';
palettes.forEach((colors,i)=>{const b=document.createElement('button');b.className=i===0?'active':'';b.title=['森林','落日','深海','黑白'][i];b.setAttribute('aria-label',b.title+'配色');colors.forEach(c=>{const s=document.createElement('span');s.className='swatch';s.style.background=c;b.append(s)});b.onclick=()=>{palette=i;document.querySelectorAll('#palettes button').forEach((el,j)=>el.classList.toggle('active',i===j));generate()};$('palettes').append(b)});
function parse(){const map=new Map(),excluded=new Set($('exclude').value.toLocaleLowerCase().split(/[\s,，]+/).filter(Boolean));const add=(word,n=1)=>{word=word.trim();if(word&&!excluded.has(word.toLocaleLowerCase())&&word.length<=60)map.set(word,(map.get(word)||0)+n)};
if(mode==='weights'){$('source').value.split('\n').forEach((line,i)=>{if(!line.trim())return;const m=line.trim().match(/^(.*?)[,，\t ]+([+-]?(?:\d*\.)?\d+)$/);if(m){const n=Number(m[2]);if(n<=0||!Number.isFinite(n))throw Error(`第 ${i+1} 行权重须大于 0`);add(m[1],n)}else add(line)})}else{const text=$('source').value.toLocaleLowerCase();const stop=new Set(`的 了 和 是 在 我 你 他 她 它 我们 你们 他们 她们 自己 与 及 或 也 都 就 而 还 又 更 仅 只 便 则 才 仍 仍然 已 已经 将 被 把 对 于 对于 关于 至于 从 自 由 向 往 到 到了 在于 以 用 为 为了 跟 同 同时 以及 及其 并 并且 而且 或者 以及 其中 通过 进行 经 经过 让 使 令 给 被 把 由 于 是 否 则 不 无 未 没 没有 不是 不会 不要 不能 不可 不必 不再 不仅 但是 但 却 可 可以 能 能够 应该 必须 需要 可能 似乎 好像 仿佛 因为 所以 如果 假如 若 那么 然后 后来 后来 已经 还是 仍然 其实 事实上 当然 只是 就是 也是 还有 还有 一些 这 这时 这个 这些 那 那时 那个 那些 这样 那样 这里 那里 其中 一个 一种 一点 一些 几个 各种 每个 所有 任何 什么 怎么 怎样 为什么 哪里 谁 何时 时候 现在 之前 以后 起来 过来 回来 出来 进去 上来 下来 看见 看到 听见 听到 觉得 知道 发现 说 说道 告诉 问道 开始 结束 结果 方面 地方 东西 事情 部分 时候 一直 一下 一会儿 一边 一共 以及 非常 比较 更加 太 最 这么 那么 多少 怎么样 的话 吧 呢 啊 哦 嗯 哈 哈哈 嘿 喂 哎 欸 嗯嗯 to the a an and of in is for on with as at by from this that it are be was were have has had not or but we you they he she its our your their`.split(/\s+/));if(!Intl.Segmenter)throw Error('此浏览器不支持中文分词，请使用词语与权重模式');for(const seg of new Intl.Segmenter('zh',{granularity:'word'}).segment(text)){if(seg.isWordLike&&(!$('autofilter').checked||(!stop.has(seg.segment)&&!/^[\p{P}\p{S}\d]+$/u.test(seg.segment))))add(seg.segment)}}return [...map].filter(([word,n])=>mode==='weights'||(Array.from(word).length>=Math.max(1,Number($('minlength').value)||2)&&n>=Math.max(1,Number($('minfreq').value)||1))).sort((a,b)=>b[1]-a[1]).slice(0,Math.max(1,Math.min(300,Number($('limit').value)||150)))}
const hardStopwords=new Set(`的 了 着 过 得 地 和 是 在 我 你 他 她 它 我们 你们 他们 她们 自己 与 及 或 也 都 就 而 还 又 更 仅 只 便 则 才 仍 仍然 已 已经 将 被 把 对 于 关于 至于 从 自 由 向 往 到 到了 在于 以 用 为 为了 跟 同 同时 以及 及其 并 并且 而且 或者 其中 通过 进行 经 经过 让 使 令 给 由 于 是否 不 无 未 没 没有 不是 不会 不要 不能 不可 不必 不再 不仅 但是 但 却 可 可以 能 能够 应该 必须 需要 可能 似乎 好像 仿佛 因为 所以 如果 假如 若 那么 然后 后来 还是 其实 事实上 当然 只是 就是 也是 还有 一些 这 这时 这个 这些 那 那时 那个 那些 这样 那样 这里 那里 一个 一种 一点 几个 各种 每个 所有 任何 什么 怎么 怎样 为什么 哪里 谁 何时 时候 现在 之前 以后 吧 呢 啊 哦 嗯 哈 哈哈 嘿 喂 哎 欸 嗯嗯 to the a an and of in is for on with as at by from this that it are be was were have has had not or but we you they he she its our your their`.split(/\s+/));
const lowInfoWords=new Set(`起来 过来 回来 出来 进去 上来 下来 看见 看到 看着 看了 看看 听见 听到 觉得 知道 不知道 发现 说 说道 说着 说的 告诉 问道 开始 结束 结果 方面 地方 东西 事情 部分 一直 一下 一会儿 一边 一共 非常 比较 更加 太 最 这么 那么 多少 怎么样 显然 终于 突然 其实 直接 真的 真正 确实 目前 后面 前面 看起来 显得 变得 成为 发生 出现 需要 希望 感谢 但是 对方 家里 先生 女士 孩子 大家 朋友 点头 点了 笑了 开口 伸手 转头 坐在 站在 走到 打开 身上 心里 眼睛 声音 房间 时间 过去 一声 一起 一样 没想到 不过 虽然 的话 都是 其他 也没有 一眼 看向 这种`.split(/\s+/));
const phraseWords=['人工智能','机器学习','深度学习','自然语言处理','用户体验','用户界面','数据分析','内容创作','项目管理','产品设计','视觉设计','时间管理','社交媒体','情感表达','家庭关系','教育培训','商业模式','心理健康','生活方式','科学技术','个人成长','问题解决'];
function parseV2(){if(mode==='weights')return parse();const excluded=new Set($('exclude').value.toLocaleLowerCase().split(/[\s,，]+/).filter(Boolean)),map=new Map(),text=$('source').value.normalize('NFC').toLocaleLowerCase();if(!Intl.Segmenter)throw Error('此浏览器不支持中文分词，请使用词语与权重模式');const raw=[...new Intl.Segmenter('zh',{granularity:'word'}).segment(text)].filter(x=>x.isWordLike).map(x=>x.segment.trim()).filter(Boolean),tokens=[];for(let i=0;i<raw.length;i++){let phrase='',matched=false;for(let j=i;j<raw.length&&j<i+6;j++){phrase+=raw[j];const candidate=phraseWords.find(p=>p===phrase);if(candidate){tokens.push(candidate);i=j;matched=true;break}if(!phraseWords.some(p=>p.startsWith(phrase)))break}if(!matched)tokens.push(raw[i])}for(const word of tokens){const normalized=word.normalize('NFC'),lower=normalized.toLocaleLowerCase(),noise=/^[\p{P}\p{S}\d]+$/u.test(normalized),single=/^[\u3400-\u9fff]$/.test(normalized),custom=customStopwords.has(lower);if($('autofilter').checked&&(hardStopwords.has(lower)||lowInfoWords.has(lower)||custom||noise||single||/^(https?|www|html|png|jpg)$/i.test(normalized)))continue;if(!excluded.has(lower)&&normalized.length<=60)map.set(normalized,(map.get(normalized)||0)+1)}let list=[...map].filter(([word,n])=>Array.from(word).length>=Math.max(1,Number($('minlength').value)||2)&&n>=Math.max(1,Number($('minfreq').value)||1));return list.map(([word,n])=>[word,n*(phraseWords.includes(word)?1.2:1)*(1+Math.min(.3,Math.log2(Math.max(1,Array.from(word).length))*.06))]).sort((a,b)=>b[1]-a[1]).slice(0,Math.max(1,Math.min(300,Number($('limit').value)||150)))}
function generate(){if(running)return;let list;try{list=parseV2()}catch(e){$('status').textContent=e.message;return}if(!list.length){$('status').textContent='请输入有效词语；排除词语后至少保留一个词。';return}if(typeof WordCloud==='undefined'){ $('status').textContent='词云组件加载失败，请刷新重试。';return}const w=Math.max(400,Math.min(2400,Number($('width').value)||1200)),h=Math.max(400,Math.min(2400,Number($('height').value)||900));$('width').value=w;$('height').value=h;canvas.width=w;canvas.height=h;$('dims').textContent=`${w} × ${h}`;const max=list[0][1],min=list[list.length-1][1],scale=w/1200;list=list.map(([word,n])=>[word,(min===max?32:16+Math.sqrt((n-min)/(max-min))*(Number($('size').value)-16))*scale]);running=true;drawn=0;total=list.length;$('generate').disabled=true;$('download').disabled=true;$('shuffle').disabled=true;$('status').textContent='正在排列文字…';const rotation=$('rotation').value;WordCloud(canvas,{list,shape,gridSize:Number($('gap').value)*scale,fontFamily:$('font').value,fontWeight:$('weight').value,backgroundColor:$('transparent').checked?'rgba(0,0,0,0)':$('bg').value,color:()=>palettes[palette][Math.floor(Math.random()*palettes[palette].length)],weightFactor:1,minSize:8*scale,rotateRatio:rotation==='flat'?0:.25,minRotation:rotation==='mixed'?-Math.PI/2:-Math.PI/3,maxRotation:rotation==='mixed'?Math.PI/2:Math.PI/3,rotationSteps:rotation==='mixed'?2:0,ellipticity:shape==='circle'?.78:1,shuffle:true,drawOutOfBound:false,shrinkToFit:true,abortThreshold:2000})}
function finish(abort=false){running=false;$('generate').disabled=false;$('download').disabled=false;$('shuffle').disabled=false;$('status').textContent=abort?`排版达到时间限制，已放置 ${drawn} / ${total} 个词。可减少词数后重试。`:`已放置 ${drawn} / ${total} 个词 · ${['圆形','心形','星形','菱形','三角','方形'][['circle','cardioid','star','diamond','triangle','square'].indexOf(shape)]}`}
canvas.addEventListener('wordclouddrawn',e=>{if(e.detail.drawn)drawn++});canvas.addEventListener('wordcloudstop',()=>finish());canvas.addEventListener('wordcloudabort',()=>finish(true));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('hint').textContent=mode==='weights'?'每行一个词，可在词后添加权重：设计, 20':'自动中英文分词，按出现频次生成，过滤常见虚词、口语词、标点和纯数字。'});
document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>{shape=b.dataset.shape;document.querySelectorAll('[data-shape]').forEach(x=>x.classList.toggle('active',x===b));generate()});
['size','gap'].forEach(id=>$(id).oninput=()=>$(id+'-out').value=$(id).value);
$('txtfile').onchange=async()=>{const file=$('txtfile').files[0];if(!file)return;if(file.size>5*1024*1024){$('fileinfo').textContent='文件超过 5 MB，请缩小后重试。';return}try{const bytes=await file.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{ text=new TextDecoder('gb18030').decode(bytes)}$('source').value=text.replace(/^\uFEFF/,'');mode='text';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='text'));$('hint').textContent='按词频统计，自动过滤常见虚词、口语词、标点和纯数字。';$('fileinfo').textContent=file.name+' · '+text.length.toLocaleString()+' 个字符';generate()}catch(e){$('fileinfo').textContent='无法读取文件，请检查文本编码。'}};
$('generate').onclick=generate;$('shuffle').onclick=generate;$('demo').onclick=()=>{$('source').value=mode==='weights'?sample:'设计源于生活，灵感源于自然。设计让文字成为艺术，让艺术走进生活。创造力连接想象与未来，自由表达让灵感生长。我们热爱设计，热爱自然，热爱生活的诗意与美好。';generate()};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p={editorial:[0,'#fbf8f1','circle','serif','mixed'],pop:[1,'#fff3df','star','sans-serif','free'],night:[2,'#142d3c','diamond','sans-serif','mixed'],mono:[3,'#fafafa','square','serif','flat']}[b.dataset.preset];palette=p[0];$('bg').value=p[1];shape=p[2];$('font').value=p[3];$('rotation').value=p[4];$('transparent').checked=false;document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('#palettes button').forEach((x,i)=>x.classList.toggle('active',i===palette));document.querySelectorAll('[data-shape]').forEach(x=>x.classList.toggle('active',x.dataset.shape===shape));generate()});
$('download').onclick=()=>canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='字有引力-词云.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png');
fetch('stopwords_custom.txt').then(response=>{if(!response.ok)throw Error('自定义停用词文件加载失败');return response.text()}).then(text=>{customStopwords=new Set(text.normalize('NFC').split(/\r?\n/).map(line=>line.replace(/#.*/,'')).join(' ').toLocaleLowerCase().split(/[\s,，]+/).filter(Boolean));generate()}).catch(error=>{$('status').textContent=error.message+'，已使用内置停用词。';generate()});
