const {contextBridge,ipcRenderer,webUtils}=require('electron');
contextBridge.exposeInMainWorld('reader',{
  cloudStatus:()=>ipcRenderer.invoke('cloud-status'),
  cloudLogin:payload=>ipcRenderer.invoke('cloud-login',payload),
  cloudLogout:()=>ipcRenderer.invoke('cloud-logout'),
  cloudConflicts:()=>ipcRenderer.invoke('cloud-conflicts'),
  cloudSync:()=>ipcRenderer.invoke('cloud-sync'),
  cloudResolve:(key,choice)=>ipcRenderer.invoke('cloud-resolve',key,choice),
  studioState:value=>ipcRenderer.invoke('studio-state',value),
  saveReview:(id,review)=>ipcRenderer.invoke('book-review',id,review),
  exportTxt:id=>ipcRenderer.invoke('export-txt',id),
  platform:process.platform,
  windowButtons:visible=>ipcRenderer.invoke('window-buttons',visible),
  copyText:text=>ipcRenderer.invoke('copy-text',text),
  cleaningPresets:()=>ipcRenderer.invoke('cleaning-presets'),
  cleaningPreview:(files,options)=>ipcRenderer.invoke('cleaning-preview',files.map(file=>webUtils.getPathForFile(file)),options),
  saveCleaning:options=>ipcRenderer.invoke('cleaning-save',options),
  exportCloud:data=>ipcRenderer.invoke('export-cloud',data),
  uiStyle:style=>ipcRenderer.invoke('ui-style',style),
  preferences:()=>ipcRenderer.invoke('preferences'),
  saveTheme:theme=>ipcRenderer.invoke('theme-save',theme),
  readingTime:payload=>ipcRenderer.invoke('reading-time',payload),
  analyze:id=>ipcRenderer.invoke('analyze',id),
  library:()=>ipcRenderer.invoke('library'), pick:()=>ipcRenderer.invoke('pick'),
  importFiles:(files,options)=>ipcRenderer.invoke('import',files.map(file=>webUtils.getPathForFile(file)),options),
  open:(id,encoding)=>ipcRenderer.invoke('open',id,encoding),
  save:payload=>ipcRenderer.invoke('save',payload), finishClose:()=>ipcRenderer.invoke('finish-close'),
  windowControl:action=>ipcRenderer.invoke('window-control',action),
  alwaysOnTop:value=>ipcRenderer.invoke('always-on-top',value),
  contextMenu:options=>ipcRenderer.invoke('context-menu',options),
  onAction:callback=>ipcRenderer.on('reader-action',(_event,action)=>callback(action)),
  onClose:callback=>ipcRenderer.on('prepare-close',()=>callback())
});
