(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./reading-analytics.js'):root.ReadingAnalytics);if(typeof module==='object'&&module.exports)module.exports=api;else root.ReadingStats=api;})(typeof globalThis!=='undefined'?globalThis:this,A=>{
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 function render(host,{days={},books=[],sessions=[]}){
  sessions=sessions.filter(s=>{try{A.validateSession(s);return true;}catch{return false;}});
  host.replaceChildren();host.classList.add('reading-dashboard');
  let appearance={layout:'portrait',palette:'sage'};try{appearance={...appearance,...JSON.parse(localStorage.getItem('readingJournalAppearance')||'{}')};}catch{}
  const palettes={sage:['鼠尾草绿','#8f9c87'],blue:['雾霾蓝','#8596a3'],rose:['烟粉豆沙','#b08c8c'],clay:['燕麦陶土','#ad917d']};
  if(!palettes[appearance.palette])appearance.palette='sage';if(!['portrait','landscape'].includes(appearance.layout))appearance.layout='portrait';
  function applyAppearance(){host.dataset.layout=appearance.layout;host.style.setProperty('--journal-accent',palettes[appearance.palette][1]);try{localStorage.setItem('readingJournalAppearance',JSON.stringify(appearance));}catch{}}
  applyAppearance();
  const journalHeader=el('div','journal-header'),mark=el('span','journal-mark','读'),title=el('div');title.append(el('h2',null,'阅读手帐'),el('p',null,'留住每一页，慢慢读过的时光。'));const settings=el('button','journal-settings','☷');settings.type='button';settings.setAttribute('aria-label','阅读手帐外观设置');settings.setAttribute('aria-expanded','false');journalHeader.append(mark,title,settings);host.append(journalHeader);
  const controls=el('div','journal-controls');controls.hidden=true;
  const layoutLabel=el('label',null,'布局'),layoutSelect=el('select');layoutSelect.setAttribute('aria-label','手帐布局');for(const [value,text]of [['portrait','竖向手帐'],['landscape','横向总览']]){const option=el('option',null,text);option.value=value;layoutSelect.append(option);}layoutSelect.value=appearance.layout;layoutSelect.onchange=()=>{appearance.layout=layoutSelect.value;applyAppearance();};layoutLabel.append(layoutSelect);
  const paletteLabel=el('label',null,'莫兰迪配色'),paletteSelect=el('select');paletteSelect.setAttribute('aria-label','手帐配色');for(const [value,[text]]of Object.entries(palettes)){const option=el('option',null,text);option.value=value;paletteSelect.append(option);}paletteSelect.value=appearance.palette;paletteSelect.onchange=()=>{appearance.palette=paletteSelect.value;applyAppearance();};paletteLabel.append(paletteSelect);controls.append(layoutLabel,paletteLabel);host.append(controls);settings.onclick=()=>{controls.hidden=!controls.hidden;settings.setAttribute('aria-expanded',String(!controls.hidden));};

  const total=Object.values(days).reduce((a,d)=>a+A.sum(d),0),today=A.dayKey(new Date());
  const recent=Array.from({length:30},(_,i)=>{const d=new Date();d.setDate(d.getDate()-29+i);return {date:A.dayKey(d),ms:A.sum(days[A.dayKey(d)])};});
  const summary=el('div','footprint-summary');
  for(const [label,ms]of [['今日阅读',A.sum(days[today])],['近七天',recent.slice(-7).reduce((a,d)=>a+d.ms,0)],['累计阅读',total]]){const n=el('div');n.append(el('span',null,label),el('strong',null,ms?A.duration(ms):'0 分钟'));summary.append(n);}host.append(summary);
  const daily=el('section','footprint-section'),heading=el('div','footprint-heading');heading.append(el('h2',null,'每日时长'));const select=el('select');select.setAttribute('aria-label','每日时长范围');for(const number of [14,30]){const option=el('option',null,`近 ${number} 天`);option.value=number;select.append(option);}heading.append(select);daily.append(heading);
  const chart=el('div','footprint-bars');chart.setAttribute('role','img');daily.append(chart);host.append(daily);
  function bars(){chart.dataset.range=select.value;const items=recent.slice(-Number(select.value)),max=Math.max(60000,...items.map(d=>d.ms));chart.replaceChildren();chart.setAttribute('aria-label',items.map(d=>`${d.date}：${d.ms?A.duration(d.ms):'0 分钟'}`).join('；'));
   items.forEach((d,i)=>{const col=el('div','footprint-bar-column');col.title=`${d.date} · ${d.ms?A.duration(d.ms):'0 分钟'}`;const bar=el('div','footprint-bar');bar.style.height=`${d.ms/max*130}px`;const label=el('small',null,i===0||i===items.length-1||i%Math.ceil(items.length/5)===0?d.date.slice(5):'');col.append(el('span',null,d.ms>=60000?Math.round(d.ms/60000):''),bar,label);chart.append(col);});}select.onchange=bars;bars();daily.append(el('p','footprint-note','单位：分钟 · 仅累计有效的前台阅读时间'));
  const calendar=el('section','footprint-section'),calHeading=el('div','footprint-heading'),nav=el('div','footprint-calendar-nav');calHeading.append(el('h2',null,'阅读日历'));const previous=el('button',null,'‹'),month=el('span'),next=el('button',null,'›');previous.setAttribute('aria-label','上个月');next.setAttribute('aria-label','下个月');nav.append(previous,month,next);calHeading.append(nav);calendar.append(calHeading);
  const weekdays=el('div','footprint-weekdays');for(const w of ['一','二','三','四','五','六','日'])weekdays.append(el('span',null,w));const grid=el('div','footprint-calendar'),dayDetail=el('p','footprint-note','点击日期查看当天阅读。');calendar.append(weekdays,grid,dayDetail);host.append(calendar);let date=new Date();date.setDate(1);
  function drawMonth(){month.textContent=`${date.getFullYear()} 年 ${date.getMonth()+1} 月`;grid.replaceChildren();for(let i=0;i<(date.getDay()+6)%7;i++)grid.append(el('span','footprint-calendar-gap'));const last=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();for(let i=1;i<=last;i++){const d=new Date(date.getFullYear(),date.getMonth(),i),key=A.dayKey(d),ms=A.sum(days[key]),button=el('button','footprint-day',i);button.dataset.level=ms===0?0:ms<600000?1:ms<1800000?2:ms<3600000?3:4;button.setAttribute('aria-label',`${key}，${ms?A.duration(ms):'无阅读记录'}`);if(key===today)button.setAttribute('aria-current','date');button.onclick=()=>{grid.querySelectorAll('[aria-pressed]').forEach(n=>n.removeAttribute('aria-pressed'));button.setAttribute('aria-pressed','true');const text=Object.entries(days[key]||{}).filter(([,v])=>v>0).map(([id,v])=>`${books.find(b=>b.id===id)?.title||'书籍'} ${A.duration(v)}`).join(' · ');dayDetail.textContent=`${key} · ${text||'没有已记录的阅读时长'}`;};grid.append(button);}}previous.onclick=()=>{date.setMonth(date.getMonth()-1);drawMonth();};next.onclick=()=>{date.setMonth(date.getMonth()+1);drawMonth();};drawMonth();calendar.append(el('p','footprint-note','颜色越深，阅读越久 · 旧数据仅保留累计时长，详细历程从新版开始记录'));
  const mode=el('div','journal-calendar-mode'),monthButton=el('button',null,'月'),yearButton=el('button',null,'年');mode.setAttribute('role','group');mode.setAttribute('aria-label','日历视图');mode.append(monthButton,yearButton);calHeading.insertBefore(mode,nav);
  const yearGrid=el('div','journal-year');yearGrid.hidden=true;calendar.insertBefore(yearGrid,dayDetail);let yearMode=false;
  function drawYear(){yearGrid.replaceChildren();month.textContent=`${date.getFullYear()} 年`;for(let m=0;m<12;m++){const tile=el('button','journal-month'),label=el('span',null,`${m+1}月`),cells=el('span','journal-mini-calendar');tile.setAttribute('aria-label',`${date.getFullYear()}年${m+1}月，打开月历`);const offset=(new Date(date.getFullYear(),m,1).getDay()+6)%7,last=new Date(date.getFullYear(),m+1,0).getDate();for(let slot=0;slot<42;slot++){const cell=el('span'),number=slot-offset+1;if(number>=1&&number<=last){const ms=A.sum(days[A.dayKey(new Date(date.getFullYear(),m,number))]);cell.dataset.level=ms===0?0:ms<600000?1:ms<1800000?2:ms<3600000?3:4;}else cell.className='journal-mini-gap';cells.append(cell);}tile.append(label,cells);tile.onclick=()=>{date.setMonth(m);setCalendar(false);};yearGrid.append(tile);}}
  function setCalendar(value){yearMode=value;grid.hidden=value;weekdays.hidden=value;yearGrid.hidden=!value;monthButton.setAttribute('aria-pressed',String(!value));yearButton.setAttribute('aria-pressed',String(value));previous.setAttribute('aria-label',value?'上一年':'上个月');next.setAttribute('aria-label',value?'下一年':'下个月');value?drawYear():drawMonth();}
  monthButton.onclick=()=>setCalendar(false);yearButton.onclick=()=>setCalendar(true);previous.onclick=()=>{yearMode?date.setFullYear(date.getFullYear()-1):date.setMonth(date.getMonth()-1);setCalendar(yearMode);};next.onclick=()=>{yearMode?date.setFullYear(date.getFullYear()+1):date.setMonth(date.getMonth()+1);setCalendar(yearMode);};setCalendar(false);
  const rankSection=el('section','footprint-section');rankSection.append(el('h2',null,'书籍时长排名'));const ranks=el('div','footprint-ranking');rankSection.append(ranks);host.append(rankSection);
  const totals={};for(const d of Object.values(days))for(const [id,value]of Object.entries(d))totals[id]=(totals[id]||0)+value;
  const ids=[...new Set([...books.map(b=>b.id),...Object.keys(totals)])].sort((a,b)=>(totals[b]||0)-(totals[a]||0));
  const detail=el('section','footprint-section footprint-book-detail');detail.setAttribute('aria-label','单书阅读历程');host.append(detail);
  function bookDetail(id){const b=books.find(b=>b.id===id),title=b?.title||'书籍';detail.replaceChildren();detail.append(el('h2',null,title+' · 阅读历程'),el('p','footprint-note',`累计 ${totals[id]?A.duration(totals[id]):'0 分钟'} · 当前进度 ${b?.counts?.total?Math.min(100,100*(b.counts.read||0)/b.counts.total).toFixed(1):'0.0'}%`));
   const records=sessions.filter(s=>s.bookId===id).sort((a,b)=>b.startedAt-a.startedAt);const timeline=el('ol','footprint-timeline');detail.append(timeline);
   if(!records.length)detail.append(el('p','footprint-empty','还没有详细历程。继续阅读后，会记录每次阅读的时间与起止位置。'));
   let visible=30;function entries(){timeline.replaceChildren();records.slice(0,visible).forEach(s=>{const li=el('li'),time=el('time',null,new Date(s.startedAt).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}));time.dateTime=new Date(s.startedAt).toISOString();const pct=v=>s.total?Math.min(100,Math.max(0,v*100/s.total)).toFixed(1):'0.0';li.append(time,el('strong',null,A.duration(s.durationMs)),el('p',null,`${pct(s.startRead)}% → ${pct(s.endRead)}%${s.endRead<s.startRead?' · 回读':''} · ${s.platform==='mobile'?'网页':'App'}`));timeline.append(li);});more.hidden=records.length<=visible;}const more=el('button','footprint-more','显示更早记录');more.onclick=()=>{visible+=30;entries();};detail.append(more);entries();
  }
  const maximum=Math.max(1,...Object.values(totals));ids.forEach((id,index)=>{const button=el('button','footprint-rank'),heading=el('span','footprint-rank-heading'),meter=el('span','footprint-rank-meter'),fill=el('span');heading.append(el('span',null,`${String(index+1).padStart(2,'0')}  ${books.find(b=>b.id===id)?.title||'书籍'}`),el('strong',null,totals[id]?A.duration(totals[id]):'0 分钟'));fill.style.width=`${(totals[id]||0)/maximum*100}%`;meter.append(fill);button.append(heading,meter);button.onclick=()=>{ranks.querySelectorAll('button').forEach(n=>n.removeAttribute('aria-current'));button.setAttribute('aria-current','true');bookDetail(id);};ranks.append(button);});if(ids.length){ranks.firstChild.setAttribute('aria-current','true');bookDetail(ids[0]);}else{ranks.append(el('p','footprint-empty','从书架打开一本书，让第一段阅读时光开始。'));detail.hidden=true;}
  const body=el('div','journal-body'),side=el('div','journal-side');side.append(daily,rankSection);body.append(calendar,side);host.insertBefore(body,detail);
 }
 return {render};
});
